package com.joohnq.moodapp.constants

object TestConstants {
    const val WELCOME_SCREEN_HORIZONTAL_PAGER = "WELCOME_SCREEN_HORIZONTAL_PAGER"
    const val WELCOME_SCREEN_RESOURCES = "WELCOME_SCREEN_INTELLIGENT"
    const val WELCOME_SCREEN_INTELLIGENT = "WELCOME_SCREEN_INTELLIGENT"
    const val WELCOME_SCREEN_HEALTH_STATE = "WELCOME_SCREEN_HEALTH_STATE"
    const val WELCOME_SCREEN_COMMUNITY = "WELCOME_SCREEN_COMMUNITY"
    const val NEXT_BUTTON = "NEXT_BUTTON"
    const val CONTINUE_BUTTON = "CONTINUE_BUTTON"

    const val ONBOARDING_ROULETTE = "ONBOARDING_ROULETTE"

    const val SLEEP_QUALITY_SLIDER = "SLEEP_QUALITY_SLIDER"
    const val TEXT_INPUT = "TEXT_INPUT"
}