name: Code review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, ready_for_review, synchronize ]
    branches: [ main ]

jobs:
  SetUp:
    runs-on: ubuntu-latest
    steps:
      - id: setVariables
        name: Set variables
        run: |
          isFromMain=${{ github.ref == 'refs/heads/main' }}
          isManual=${{ github.event_name == 'workflow_dispatch' }}
          hasKmpLabel=${{ contains(github.event.pull_request.labels.*.name, 'KMP') }}
          shouldRunKmp=false
          if $isFromMain || $isManual || $hasKmpLabel ; then
            shouldRunKmp=true
          fi
          echo "shouldRunKmp=$shouldRunKmp" >> "$GITHUB_OUTPUT"
          echo "shouldRunAndroid=${{ contains(github.event.pull_request.labels.*.name, 'Android') }}" >> "$GITHUB_OUTPUT"
          echo "shouldRunIos=${{ contains(github.event.pull_request.labels.*.name, 'iOS') }}" >> "$GITHUB_OUTPUT"
          
          if [ "$isFromMain" == "true" ] || [ "$isManual" == "true" ] || ([ ${{ github.event_name }} == pull_request ] && [ ${{ github.event.pull_request.draft }} == false ]); then
            exit 0
          else
            exit 1
          fi
    outputs:
      shouldRunKmp: ${{ steps.setVariables.outputs.shouldRunKmp }}
      shouldRunAndroid: ${{ steps.setVariables.outputs.shouldRunAndroid }}
      shouldRunIos: ${{ steps.setVariables.outputs.shouldRunIos }}

  Build:
    needs: SetUp
    uses: ./.github/workflows/build.yml
    with:
      shouldRunKmp: ${{ needs.SetUp.outputs.shouldRunKmp }}
      shouldRunAndroid: ${{ needs.SetUp.outputs.shouldRunAndroid }}
      shouldRunIos: ${{ needs.SetUp.outputs.shouldRunIos }}

  UnitTests:
    needs: SetUp
    uses: ./.github/workflows/test.yml
    with:
      shouldRunKmp: ${{ needs.SetUp.outputs.shouldRunKmp }}
      shouldRunAndroid: ${{ needs.SetUp.outputs.shouldRunAndroid }}
      shouldRunIos: ${{ needs.SetUp.outputs.shouldRunIos }}

  AllowMerge:
    if: always()
    runs-on: ubuntu-latest
    needs: [ Build, UnitTests ]
    steps:
      - run: |
          echo "Labels: ${{ join(github.event.pull_request.labels.*.name) }}"
          echo "Build result: ${{ needs.Build.result }}"
          echo "UnitTests result: ${{ needs.UnitTests.result }}"

          if [ "${{ github.event_name }}" == "pull_request" ] && [ -z "${{ github.event.pull_request.labels.*.name }}" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "Skipping merge: No labels found."
            exit 1
          fi

          if [[ "${{ needs.Build.result }}" == "failure" ]] || [[ "${{ needs.UnitTests.result }}" == "failure" ]]; then
            echo "Skipping merge: Build or UnitTests failed."
            exit 1
          fi

          echo "All checks passed. Allowing merge."
          exit 0

  Distribute:
    name: Distribute bundle to Google Play
    needs: [ Build, UnitTests ]
    runs-on: ubuntu-latest
    if: needs.AllowMerge.result == 'success'  # Garante que só roda se AllowMerge passar

    steps:
      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: composeApp/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: composeApp/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.joohnq.moodapp
          releaseFiles: composeApp/build/outputs/bundle/release/Mood-v${{ github.run_number }}-release.aab
          track: 'internal'
          status: 'draft'
