name: Deploy To Google Play

on:
  push:
    branches: [ release ]

jobs:
  test:
    name: Unit Test and Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Decode google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > composeApp/google-services.json

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run SpotlessCheck
        run: ./gradlew spotlessCheck

      - name: Run Unit Tests
        run: ./gradlew test

  distribute:
    name: Distribute bundle to Google Play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Decode google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > composeApp/google-services.json

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: composeApp/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: composeApp/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.joohnq.moodapp
          releaseFiles: composeApp/build/outputs/bundle/release/Moodly-v${{ github.run_number }}-release.aab
          track: 'internal'
          status: 'completed'